# Generated by Django 5.2 on 2025-06-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_store', '0007_alter_product_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_producto',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
