# Generated by Django 5.2 on 2025-04-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_direccion_comuna_alter_direccion_region_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
